###
GET http://localhost:8080/events
###
GET http://localhost:8080/events/5

###
DELETE  http://localhost:8080/events/4


### 
POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ5Mzg5NTM4LCJ1c2VySWQiOjF9.UcB42a8wf1LUWIWjV5s-lZ3Ebfzq08AHFrNX-JiHrfk

{
	"name": "Test-3",
	"description": "Test Description-3",
	"location":"Chittogram,Bangladesh",
	"date_time":"2025-05-01T15:30:00.00Z"
}


###
PUT http://localhost:8080/events/4
Content-Type: application/json

{
	"name": "Updated",
	"description": "Updated-1",
	"location":"Thakurga,Bangladesh",
	"date_time":"2025-05-01T15:40:00.00Z"
}