###
GET http://localhost:8080/events
###
GET http://localhost:8080/events/3

###
DELETE  http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ5NDU3MDIxLCJ1c2VySWQiOjF9.CCGBwlLm92xQSgC1cAMpLyX5eCmhqsWN44LC-s9btqA


### test token
POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ5NDYzNjg1LCJ1c2VySWQiOjF9.4uGoIqSfW3yUhEn-N9AvreedBvucLJRqQ06edi5GkqI

{
	"name": "Test-Event",
	"description": "Test Description",
	"location":"Chittogram,Bangladesh",
	"date_time":"2025-05-01T15:30:00.00Z"
}


### test2 token
PUT http://localhost:8080/events/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ5NDU3MDIxLCJ1c2VySWQiOjF9.CCGBwlLm92xQSgC1cAMpLyX5eCmhqsWN44LC-s9btqA

# test2 token

# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0OTQ2MDI2NCwidXNlcklkIjoyfQ.DpO3dUpNUmdi8FImLDyMZ4kyQhrOejIWL5rP3TR-RaA

{
	"name": "Updated",
	"description": "Updated-1",
	"location":"Thakurga,Bangladesh",
	"date_time":"2025-05-01T15:40:00.00Z"
}